# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo/viz_service

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install pipenv
            cd /app && pipenv lock --requirements > requirements.txt
            pip install -r /app/requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            python -m unittest test_temp.MyTestCase in /tests
