name: viz_service tests

on: [push]

defaults:
  run:
    working-directory: ./viz_service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          ls -la
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install python packages
        run: |
          pipenv install
          pip freeze

      - name: Test flask app
        run: |
          python -m unittest discover -p "test_flask_app.py"

      - name: Test transformation functions
        run: python -m unittest discover -p "test_data_transformation_functions"