name: viz_service tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    evn:
      working-directory: ./viz_service
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
        working-directory: ${{env.working-directory}}

      - name: Test flask app
        run: |
          python -m unittest discover -p "test_flask_app.py"
        working-directory: ${{env.working-directory}}
        
      - name: Test transformation functions
        run: python -m unittest discover -p "test_data_transformation_functions"
        working-directory: ./viz_service